groups:
  - name: node
    rules:
      - alert: LowDiskSpace
        expr: 100 * node_filesystem_free_bytes{job="nodes"} / node_filesystem_size_bytes{job="nodes"} < 10
        labels:
          severity: warning
          environment: prod
      - alert: NodeDown
        expr: up{job="nodes"} == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          message: "node {{.Labels.instance}} is down"
      - alert: HostOutOfMemory
        expr: node_memory_MemAvailable_bytes{job="nodes"} / node_memory_MemTotal_bytes{job="nodes"} * 100 < 10
        labels:
          severity: warning
          team: internal-infra
        annotations:
          message: "node {{.Labels.instance}} is seeing high memory usage, currently available memory: {{.Value}}%"
          